export const info = {
    name: 'youdao',
    icon: 'logo/youdao.svg',
};

// https://ai.youdao.com/DOCSIRMA/html/trans/api/wbfy/index.html
export enum Language {
    auto = 'auto',
    zh_cn = 'zh_cn',
    zh_tw = 'zh_tw',
    en = 'en',
    ja = 'ja',
    ko = 'ko',
    fr = 'fr',
    es = 'es',
    ru = 'ru',
    de = 'de',
    it = 'it',
    tr = 'tr',
    pt_pt = 'pt_pt',
    pt_br = 'pt_br',
    vi = 'vi',
    id = 'id',
    th = 'th',
    ms = 'ms',
    ar = 'ar',
    hi = 'hi',
    km = 'km',
    nb_no = 'nb_no',
    nn_no = 'nn_no',
    fa = 'fa',
    sv = 'sv',
    pl = 'pl',
    nl = 'nl',
    uk = 'uk',
    he = 'he',
}
